### ISSUE TITLE
Expose lookups via hash itself

### ISSUE THREAD

**Issue by iand675** [tibbe/unordered-containers#106]
I've got some code where the Hashable instance is a little bit expensive to calculate repeatedly, but there's a mostly-fixed set of keys that are used. It would be very handy to be able to just calculate the hash myself and memoize it for use in lookups with a function `lookupByHash :: Int -> HashMap k v`.

**Comment by tibbe** [comment]
`lookupByHash` is a bit clumsy to implement since it might return more than one value due to hash collisions. How about something like this to cache the hash computation?

```haskell
newtype Cached = C !Int !MyType

instance Hashable Cached where
    hash (C h _) = h

mkCached :: MyType -> Cached
mkCached x = C (hash x) x
```

**Comment by iand675** [comment]
Hey, that's clever! I don't think it could be a newtype though. Is this the sort of thing that would be worth putting into either hashable or unordered-containers?

**Comment by tibbe** [comment]
Right, it should be a data type. I've thought about adding it into hashable, but we would have to go with this:

```haskell
newtype Cached = C !Int !a
```

and that `a` doesn't unpack, which is typically what you want.

**Comment by bgamari** [comment]
For the record, `Cached` is now included in `hashable` as `Data.Hashable.Hashed`.
