### ISSUE TITLE
Add instance for `Data.Unique.Unique` from `base.

### ISSUE THREAD

**Issue by ekmett** [tibbe/unordered-containers#110]
It is just an `Integer` in disguise and provides `hashUnique` to extract a hash.

We can just take that as our `hash`.

```haskell
instance Hashable Unique where
  hashWithSalt i u = hashWithSalt i (hashUnique u) 
  hash = hashUnique
```

Then `HashMap Unique` works without orphans.

**Comment by tibbe** [comment]
Pull requests welcome. :)

**Comment by phadej** [comment]
AFAICS this is done.

**Comment by ekmett** [comment]
indeed
