### ISSUE TITLE
Using SmallArray#

### ISSUE THREAD

**Issue by AndrasKovacs** [tibbe/unordered-containers#126]
It's been a while since Johan added SmallArray# to GHC. Is there a reason to not use it here? Searching this repository didn't bring up relevant discussion. I did some benchmarking and it overall it showed improvement  (here's a [data dump](http://lpaste.net/153003)).

**Comment by tibbe** [comment]
Makes sense. We need to support the last three major versions of GHC, so
you might need to add some ifdefs in the Array module.

**Comment by bgamari** [comment]
I believe `SmallArray` was added in 7.10, so in principle support could be added after the GHC 8.2 release without the `ifdefs` (although retaining compatibility would probably be worthwhile). @AndrasKovacs, do you have a patch for this?

**Comment by treeowl** [comment]
Closed by #164.
