### ISSUE TITLE
Add Hashable instances for HashSet, HashMap

### ISSUE THREAD

**Issue by rwbarton** [tibbe/unordered-containers#128]
These are useful for memoizing higher-order functions.

Care must be taken to use a commutative and associative operation when combining hashes of entries involved in a hash collision. (The easy definition `hash h = hash (toList h)` is not correct.)

**Comment by phadej** [comment]
AFAICS they are there already in newest release: https://github.com/tibbe/unordered-containers/blob/v0.2.7.0/Data/HashSet.hs#L156

**Comment by rwbarton** [comment]
Yes, they are. I had an older version installed. Thanks!
