### ISSUE TITLE
Order of toList

### ISSUE THREAD

**Issue by qrilka** [tibbe/unordered-containers#131]
Am I correct assuming that `Data.HashMap.Strict.toList` returns hashmap key-value pairs always in sorted order as a result of hashmap internal structure? If so probably it's worth a note in haddocks about it?

**Comment by tibbe** [comment]
That's correct. Would you mind submitting a pull request? I would recommend a wording along the lines of "the order of the elements is unspecified", instead of talking about the internal structure.

**Comment by qrilka** [comment]
I'd like too but I'm somewhat confused here - if I'm correct and it gives key sorted list of pairs then why do you talk about unspecified order?

**Comment by tibbe** [comment]
I read your reply too hastily. It doesn't return the keys in sorted order, as the internal structure is sorted by hash value, not key value.

**Comment by qrilka** [comment]
ok, thanks, now it's totally clear.
Actually I see
```
A HashMap makes no guarantees as to the order of its elements.
```
in module haddocks which is also clear enough though not quite close to `toList` definition so I've created #132
