### ISSUE TITLE
Time complexity of `HashSet.member` is O(log(n))?

### ISSUE THREAD

**Issue by vaibhavsagar** [tibbe/unordered-containers#144]
The time complexity of `member` is stated to be _O(min(n,W))_ but its implementation is identical to `HashMap.member` whose time complexity is stated as _O(log n)_. Is the documentation incorrect or is there something I'm missing?

**Comment by tibbe** [comment]
That's a bug. It should be O(log n). This is a left-over from the previous implementation.
