### ISSUE TITLE
Data.HashMap.Strict.unsafeInsertWith has a strictness bug

### ISSUE THREAD

**Issue by treeowl** [tibbe/unordered-containers#150]
In

```haskell
    go h k x s (Leaf hy l@(L ky y))
        | hy == h = if ky == k
                    then return $! leaf h k (f x y)
                    else do
                        let l' = x `seq` (L k x)
                        return $! collision h l l'
        | otherwise = two s h k x hy ky y
```

the `otherwise` case doesn't force `x`. Note that `two` is imported from `Data.HashMap.Base` and does not force its argument.

**Comment by tibbe** [comment]
Well spotted. Do you mind putting together a pull request with a fix and perhaps add a test in https://github.com/tibbe/unordered-containers/blob/master/tests/Strictness.hs ?

**Comment by treeowl** [comment]
@tibbe Pull request submitted for fix and test.
