### ISSUE TITLE
Compilation failures on older GHCs

### ISSUE THREAD

**Issue by phadej** [tibbe/unordered-containers#179]
*EDIT* I tested current `master`

What's the oldest supported GHC? Because I see:

## GHC-7.0.2

```
Data/HashMap/Lazy.hs:2:14-24: Unsupported extension: Trustworthy
```

## GHC-7.2.2, GHC-7.4.2, GHC-7.6.3

```
Data/HashMap/Base.hs:4:14-28:
    Unsupported extension: RoleAnnotations
```

---

I volunteer to fix issues (and regenerate `.travis.yml` to test older GHC as well), just tell me what you want to support.

**Comment by treeowl** [comment]
Do you need them? Why? We actually removed support in the interest of
getting rid of clutter. If we need to revert, you should find that fairly
recent commit helpful. But this all has to happen quick--I want to release
today.

**Comment by phadej** [comment]
@treeowl I don't personally need support for older GHC. I pre-emptively contact you as Hackage Trustee.

Could you mind adding `base >= 4.7 && <5` bound (now it's `base ==4.*`) (or/and maybe `other-extensions: RoleAnnotations`, that would guide cabal solver too)

cc @hvr

**Comment by treeowl** [comment]
I'll do both. Thanks.

**Comment by treeowl** [comment]
`.cabal` updated.
