### ISSUE TITLE
Why doesn't 'traverseWithKey' of Data.HashMap.Strict ensure the values of the result in WHNF?

### ISSUE THREAD

**Issue by pierric** [tibbe/unordered-containers#192]
I find a strict version of `traverseWithKey` is missing from Data.HashMap.Strict.Base. Instead I only see following sentence: 
> -- TODO: Should we add a strict traverseWithKey?

Is there any particular reason not to implement it?

I recent chased a memory leak in my program, and eventually find out that the values of my result HashMap after calling traverseWithKey are not in WHNF. This somewhat breaks the meaning of the whole module.

**Comment by treeowl** [comment]
No, I don't think there's a good reason. Let's fix that, shall we?

**Comment by pierric** [comment]
sure. I will make a PR :)

**Comment by pierric** [comment]
I find it actually difficult to defined a completely strict version. there are various issues.  The `traverseWithKey` only requires `Functor`, but there seems not similar thing to `<$!>` with `Functor`.  

There is also a issue with `<$!>` with `Monad` here. https://stackoverflow.com/questions/9423622/strict-fmap-using-only-functor-not-monad

**Comment by treeowl** [comment]
I'm not sure what you're saying. `traverseWithKey` deals with `Applicative`, not `Functor`. You're not going to want to implement the strict version using the lazy version; you'll want to copy the code and make the necessary changes. But remember: you don't need to force elements before producing an action (and you can't). You need to force elements before producing a result. Specification:

```
Strict.traverseWithKey f = fmap (Strict.map id) . Lazy.traverseWithKey f
```

**Comment by pierric** [comment]
i am sorry that i wasn't able to make a response earlier. I was thinking about Applicative, but typed Functor instead. I am just concerning about is there a universal way to force the value there. 

I made following test case. I tried three different monad, IO, Identity, and a strict Identity. I find OOM is solved in case 1, case 3, but no case 2, with your fix.  The same occurs in my fix here https://github.com/pierric/unordered-containers/commit/b975384ee6c636248a25de8e2cb9c4b2735ab0b8

```
{-# LANGUAGE BangPatterns #-}
module Main where

import Control.Monad.Identity
import qualified Data.HashMap.Strict as M
import qualified Data.Vector.Storable as V

mkV :: Int -> IO (V.Vector Int)
mkV = V.replicateM (128 * 1024) . return

main :: IO ()
main = do
    vs <- mapM mkV [1..100]
    let m0 = M.fromList (map (\v -> (v V.! 0, v)) vs)
    --
    -- case 1. IO monad
    go 100000000 m0
    --
    -- case 2. Identity monad
    -- return $! runIdentity $ go 100000000 m0
    --
    -- case 3. SI monad
    -- return $! runSI $ go 100000000 m0

go 0 _ = return ()
go !cnt !mi = do
    mj <- flip M.traverseWithKey mi $ \k v -> return $ V.map (+1) v
    go (cnt - 1) mj
    


newtype SI a = SI { runSI :: a }
--- strict fmap: OOM free
instance Functor SI where
  fmap f (SI a) = SI $! f $! a
-- lazy fmap: OOM!!!
-- instance Functor SI where
--  fmap f a = SI $ f $ runSI a
instance Applicative SI where
  pure !a = SI a
  SI a <*> SI (!b) = let !c = a b in SI c
instance Monad SI where
  SI !a >>= f = f a
```

**Comment by treeowl** [comment]
Ah, I think I understand what happened. There's a bit of an inconsistency. Whereas `Lazy.mapWithKey` forces the structure of the tree, `Lazy.traverseWithKey` does not. For the strict traversal function to work right with `Identity`, we need to be stricter. Please try the version I just pushed; I think I probably fixed it.

**Comment by pierric** [comment]
I confirm that the OOM is gone with Identity monad. Great! Thank you very much  @treeowl

**Comment by treeowl** [comment]
Thanks for helping me pin this down, @pierric!
