### ISSUE TITLE
Work with GHC 8.6

### ISSUE THREAD

**Issue by vaibhavsagar** [tibbe/unordered-containers#214]
`unordered-containers-0.2.9.0` uses `Data.Map.fold` in `tests/HashMapProperties.hs` which prevents the tests from compiling and running. I see that this has been fixed in 230004449a87b57d53dbc0a622e161854c6eb754 so it looks like a new release is all that is necessary. I have a Nix expression for the current `HEAD` that appears to work:

```nix
let
  fetcher = { owner, repo, rev, sha256 }: builtins.fetchTarball {
    inherit sha256;
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
  };
  nixpkgs' = fetcher {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "9bbb84f622e8c421419e6ca9949a5b55e25c4be8";
    sha256 = "0kv30544nl7a33icd952ya4zkwrqjla53cdpiqhmyng9kyd3zbrp";
  };
  nixpkgs = import nixpkgs' {};
in (nixpkgs.haskell.packages.ghc861.extend(self: super: {
  ChasingBottoms    = nixpkgs.haskell.lib.doJailbreak super.ChasingBottoms;
  hashable          = nixpkgs.haskell.lib.doJailbreak super.hashable;
  primitive         = self.callHackage "primitive" "0.6.4.0" {};
  test-framework    = nixpkgs.haskell.lib.doJailbreak super.test-framework;
})).callCabal2nix "unordered-containers" ./. {}
```

**Comment by peti** [comment]
Ping? Will you release an update that compiles with GHC 8.6.1?

**Comment by treeowl** [comment]
Yes.

**Comment by treeowl** [comment]
Thanks to [GHC Trac #15696](http://ghc.haskell.org/trac/ghc/ticket/15696), GHC 8.6.1 is unusably broken anyway, so I think I have another couple days to release this package for 8.6.2.

**Comment by treeowl** [comment]
I haven't forgotten about this. There's some work going on in the background on another issue that I hope to be able to merge for the next release.

**Comment by peti** [comment]
Broken on ghc 8.6.x for 5 months and counting ...

**Comment by treeowl** [comment]
*sigh*. Yes, I will fix that today. I'm very sorry.

**Comment by vaibhavsagar** [comment]
This isn't urgent for me, but have you been able to cut a new release yet?

**Comment by treeowl** [comment]
A release has been cut!

**Comment by vaibhavsagar** [comment]
Thank you!
