### ISSUE TITLE
No `Eq`

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tibbe/unordered-containers#244]
Any thoughts on not depending on the `Eq` for a faster lookup and smaller footprint when collisions are not a major issue?

**Comment by treeowl** [comment]
Do you have a realistic application where this behavior would actually be acceptable?

**Comment by BebeSparkelSparkel** [comment]
I have a tokenized search that has the suggestions paired with a hashable token (some subset of the suggestion's text). In the search if a clash occurs the user will not choose the incorrect suggestions.
If the tokens could be garbage collected and just the hashes remained there would be considerable savings with the amount of memory used.

**Comment by treeowl** [comment]
So what you're really looking for is an `IntMap` or `WordMap` implemented as an array-mapped trie?

**Comment by BebeSparkelSparkel** [comment]
A very intriguing suggestion. I'll look into array-mapped tries.
Thank you
