### ISSUE TITLE
Suggestion: provide Hashable instances for containers themselves

### ISSUE THREAD

**Issue by nikita-volkov** [tibbe/unordered-containers#78]

**Comment by phadej** [comment]
Yes, I found https://issues.apache.org/jira/browse/THRIFT-1927 and that implementation is just so incorrect, it makes me very sad :(

**Comment by phadej** [comment]
Also: don't open issues on April's Fool day.

**Comment by andrewthad** [comment]
I think this can be closed.

**Comment by treeowl** [comment]
Closed in #111
