### ISSUE TITLE
Allow conversion between HashSets and HashMaps.

### ISSUE THREAD

**Issue by DanielWaterworth** [tibbe/unordered-containers#87]
It would be really useful if there were two functions:

```
toMap :: (Hashable k, Eq k) => HashSet k -> HashMap k ()
fromMap :: (Hashable k, Eq k) => HashMap k () -> HashSet k
```

because it would make intersection and difference of mixed hashsets and hashmaps possible.

**Comment by ivan-m** [comment]
I've just been bitten by this; any chance this will be added?

(Not even using `Data.Coerce` works, as the `HashSet` constructor isn't exported.)

**Comment by tibbe** [comment]
I'd accept a pull request. :)

**Comment by DanielWaterworth** [comment]
:)
