### ISSUE TITLE
unordered-containers-0.2.5.1 test suite doesn't compile with ghc 7.4.2

### ISSUE THREAD

**Issue by peti** [tibbe/unordered-containers#96]
I'm getting these errors:

    Preprocessing test suite 'hashset-properties' for
    unordered-containers-0.2.5.1...

    tests/HashSetProperties.hs:79:0:
         error: missing binary operator before token "("
         #if MIN_VERSION_containers(0,4,2)
         ^

    tests/HashSetProperties.hs:89:0:
         error: missing binary operator before token "("
         #if MIN_VERSION_containers(0,4,2)
         ^

Is this an issue with Cabal, maybe?

**Comment by tibbe** [comment]
This looks like a cabal issue. The generated `cabal_macros.h` file doesn't contain that macro:

```
$ cat dist/build/autogen/cabal_macros.h
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package base-4.5.1.0 */
#define VERSION_base "4.5.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  5 || \
  (major1) == 4 && (major2) == 5 && (minor) <= 1)

/* package deepseq-1.3.0.0 */
#define VERSION_deepseq "1.3.0.0"
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)

/* package hashable-1.2.3.1 */
#define VERSION_hashable "1.2.3.1"
#define MIN_VERSION_hashable(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
```

Solution would be to upgrade Cabal. We're unlikely to backport a fix to Cabal 1.18 for this.
